config/routes.rb
Rails.application.routes.draw do
  resources :course_stores
  resources :instructors
    resources :requests,    only: [:create, :destroy, :update]
    resources :courses do
        member do
            get :accept_requests
        end
    end
    get 'sessions/new'   
    resources :users do
              member do
            get :request_course
            get :courses
        end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'users#index'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/error', :to => redirect('/404.html')
    get '/error', to:'instructors#show'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    validates :name, :presence => true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :email,:presence =>true, :uniqueness => true
 
    validates :password, :presence => true, :length => { :in => 6..20 }
    has_secure_password
    validate :unique_name

    def unique_name
        self.errors.add(:email, 'is already taken') if User.where(email: self.email).exists?
    end
 end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit,:update,:show] 
  before_action :correct_user, only: [:edit,:update,:show]
  #  before_action :correct_user_admin, only: [:index]
 
 
  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
     @courses = Course.all
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end
    def logged_in_user
        unless logged_in?
            store_location
            redirect_to login_url
        end
    end

    def correct_user
        @user = Instructor.find(params[:id])
        @user1 = Instructor.find_by(email: session[:user_id])
        redirect_to @user1 unless current_user?(@user)
    end

    def correct_user_admin
         @user1 = Instructor.find_by(email: session[:user_id])
        redirect_to @user1 unless current_user_admin?
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :dept, :password, :email, :password_confirmation)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= stylesheet_link_tag "form_design.css" %>
<div class="form_design">
<%= form_for(instructor) do |f| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :dept %>
    <%= f.text_field :dept %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

   <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>  

app/views/instructors/edit.html.erb
<%= stylesheet_link_tag "navigation_bar.css" %>
<ul>
     <li class="left"><%= link_to 'Home', instructor_path(@instructor) %></li>
     <li class="left active"><%= link_to 'Edit Personal Details', edit_instructor_path(@instructor) %></li>
     <li class="left"><%= link_to 'List of All Instructors', instructors_path(current_user) %></li>
     <li class="left"><%= link_to "Course Requests", accept_requests_course_path(current_user) %></li>
     <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
     <li class="right"><a><%= current_user.name %></a></li>
</ul>


<h1>Please Update Your Details</h1>

<%= render 'form', instructor: @instructor %>

app/views/instructors/index.html.erb
<%= stylesheet_link_tag "table_design.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>

<ul>
     <li class="left"><%= link_to 'Home', instructor_path(current_user) %></li>
     <li class="left"><%= link_to 'Edit Personal Details', edit_instructor_path(current_user) %></li>
     <li class="left active"><%= link_to 'List of All Instructors', instructors_path(current_user) %></li>
     <li class="left"><%= link_to "Course Requests", accept_requests_course_path(current_user) %></li>
     <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
     <li class="right"><a><%= current_user.name %></a></li>
</ul>

<p id="notice"><%= notice %></p>

<h1>List of All Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dept</th>
      <th>Email</th>
      <% if current_user.admin %>
          <th colspan="3" style="color:red; text-align: center"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.name %></td>
        <td><%= instructor.dept %></td>
        <td><%= instructor.email %></td>
        <% if current_user.admin %>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<%= stylesheet_link_tag "show_details.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<%= stylesheet_link_tag "table_design.css" %>

<ul>
    <li class="left"><a class="active">Home</a></li>
    <li class="left"><%= link_to 'Edit Personal Details', edit_instructor_path(@instructor) %></li>
    <li class="left"><%= link_to 'List of All Instructors', instructors_path(current_user) %></li>
    <li class="left"><%= link_to "Course Requests", accept_requests_course_path(current_user) %></li>
    <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
    <li class="right"><a><%= current_user.name %></a></li>
</ul>

<p id="notice"><%= notice %></p>

<div class="show">
<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @instructor.dept %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>
</div>
<br>
<hr>

<h2 style="text-align:center; margin-top:10px; color: red">Pre-Registration Dates for 2016-17 2nd Semester</h2>
<h2 style="text-align:center; color: purple">1st November 2016 - 8th November 2016</h2>

<hr>

<h2 style="text-align:center; margin-top:30px">Courses Offered Next Semester</h2>

<table>
  <thead>
    <tr>
      <th>Dept</th>
      <th>Code</th>
      <th>Title</th>
      <th>Instructor</th>
      <th>Email</th>
      <th>Credit</th>
      <th>Timing</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.dept %></td>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= course.instructor %></td>
        <td><%= course.email %></td>
        <td><%= course.credit %></td>
        <td><%= course.timing %></td>
        <td><%= link_to 'Show', course %></td>
      </tr>
    <% end %>
  </tbody>
</table>