config/routes.rb
Rails.application.routes.draw do
  resources :course_stores
  resources :instructors
    resources :requests,    only: [:create, :destroy, :update]
    resources :courses do
        member do
            get :accept_requests
        end
    end
    get 'sessions/new'   
    resources :users do
              member do
            get :request_course
            get :courses
        end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'users#index'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/error', :to => redirect('/404.html')
    get '/error', to:'instructors#show'
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :presence => true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :email,:presence =>true, :uniqueness => true
    validates :roll, :presence => true
    validates :phone, :presence => true, :length => { :is => 10 }
    validates :dob, :presence => true
    validates :address, :presence => true
    validates :password, :presence => true, :length => { :in => 6..20 }
    has_secure_password
    has_many :course_requests, class_name: "Request", foreign_key: "user_id", dependent: :destroy
    has_many :courses, through: :course_requests
    validate :unique_name
    has_many :completed_courses, -> { where grade: ['A*', 'A', 'B', 'C', 'D', 'E', 'F'] }, class_name: "CourseStore", foreign_key: "user_id"
    has_many :ongoing_courses, -> { where grade: 'ongoing'}, class_name: "CourseStore", foreign_key: "user_id"
 
    def unique_name
        self.errors.add(:email, 'is already taken') if Instructor.where(email: self.email).exists?
    end

    def request(course)
        course_requests.create(course_id: course.id, status: "Waiting")
    end

    def delete_request(course)
        course_requests.find_by(course_id: course.id).destroy
    end

    def requested?(course)
        courses.include?(course)
    end

    def accepted?(course)
        return course_requests.find_by(course_id: course.id).status == "Accepted"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :request_course,:courses] 
  before_action :correct_user, only: [:show,:edit,:update,:request_course,:courses]
  before_action :correct_user_admin, only: [:index]
 
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @courses = Course.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /user/:id/request_course
  def request_course
    @user = User.find(params[:id])
    @requested_courses = @user.courses
    @courses = Course.all
  end

  # GET /user/:id/courses
  def courses
    @user = User.find(params[:id])
    @ongoing_courses = @user.ongoing_courses
    @completed_courses = @user.completed_courses
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def logged_in_user
        unless logged_in?
            store_location
            redirect_to login_url
        end
    end

    def correct_user_admin
        redirect_back_or(root_url) unless current_user_admin?
    end


    def correct_user
        @user = User.find(params[:id])
        redirect_to('/404.html') unless current_user?(@user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :roll, :phone, :address, :dob, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_delete.html.erb
<%= form_for(course.user_requests.find_by(user_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Delete", class: "btn" %>
<% end %>

app/views/users/_form.html.erb
<%= stylesheet_link_tag "form_design.css" %>
<div class = "form_design">
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :roll %>
    <%= f.number_field :roll %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :dob %>
    <%= f.text_field :dob  %>
  </div>

   <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

   <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div> 

app/views/users/_request.html.erb
<%= form_for(course.user_requests.build) do |f| %>
  <div><%= hidden_field_tag :user_id, @user.id %></div>
  <div><%= hidden_field_tag :course_id, course.id %></div>
  <%= f.submit "Request", class: "btn btn-primary" %>
<% end %>

app/views/users/courses.html.erb
<%= stylesheet_link_tag "table_design.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<p id="notice"><%= notice %></p>

<ul>
     <li class="left"><a href="../../">Home</a></li>
     <li class="left active"><%= link_to "Transcript", courses_user_path(current_user) %></li>
     <li class="left"><%= link_to "Course Request", request_course_user_path(current_user) %></li>
     <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
     <li class="right"><a><%= current_user.name %></a></li>
 </ul>

<h1>Ongoing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Credit</th>
      <th>Semester</th>
      <th>Grade</th>
    </tr>
  </thead>

  <tbody>
    <% @ongoing_courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.code %></td>
        <td><%= course.credit %></td>
        <td><%= course.sem %></td>
        <td><%= course.grade %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Completed Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Credit</th>
      <th>Semester</th>
      <th>Grade</th>
    </tr>
  </thead>

  <tbody>
    <% @completed_courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.code %></td>
        <td><%= course.credit %></td>
        <td><%= course.sem %></td>
        <td><%= course.grade %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "navigation_bar.css" %>
<%= stylesheet_link_tag "table_design.css" %>
<ul>
    <li class="left"><a class="active">Home</a></li>
    <li class="left"><%= link_to "Transcript", courses_user_path(current_user) %></li>
    <li class="left"><%= link_to "Course Request", request_course_user_path(current_user) %></li>
    <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
    <li class="right"><a><%= current_user.name %></a></li>
</ul>
<p id="notice"><%= notice %></p>

<h2 style="text-align:center; margin-top: 60px; color: red">Pre-Registration Dates for 2016-17 2nd Semester</h2>
<h2 style="text-align:center; color: purple">1st November 2016 - 8th November 2016</h2>

<hr>

<h1 style="margin-top:20px">Users</h1>

<table id="user_data">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Roll</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Dob</th>
        <th colspan="3">Other Options</th>
    </tr>    
    <% @users.each do |user| %>
    <tr>    
        <td><%= user.name %></td>
        <td><%= user.email %></td>   
        <td><%= user.roll %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td><%= user.dob %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/request_course.html.erb
<%= stylesheet_link_tag "table_design.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<ul>
    <li class="left"><a href="../../">Home</a></li>
    <li class="left"><%= link_to "Transcript", courses_user_path(current_user) %></li>
    <li class="left active"><%= link_to "Course Request", request_course_user_path(current_user) %></li>
    <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
    <li class="right"><a><%= current_user.name %></a></li>
</ul>
<p id="notice"><%= notice %></p>

<h1>Requested Courses</h1>

<table>
  <thead>
    <tr>
      <th>Dept</th>
      <th>Code</th>
      <th>Title</th>
      <th>Instructor</th>
      <th>Credit</th>
      <th>Timing</th>
      <th>Status</th>
      <th>Request</th>
    </tr>
  </thead>

  <tbody>
    <% @requested_courses.each do |course| %>
      <tr>
        <td><%= course.dept %></td>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= course.instructor %></td>
        <td><%= course.credit %></td>
        <td><%= course.timing %></td>
        <td><%= course.user_requests.find_by(user_id: @user.id).status %></td> 
        <td> <% if @user.requested?(course) && !@user.accepted?(course)%>
                <%= render 'delete', course: course %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<h1>Available Courses</h1>

<table>
  <thead>
    <tr>
      <th>Dept</th>
      <th>Code</th>
      <th>Title</th>
      <th>Instructor</th>
      <th>Credit</th>
      <th>Timing</th>
      <th>Request</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.dept %></td>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= course.instructor %></td>
        <td><%= course.credit %></td>
        <td><%= course.timing %></td>
        <td> <% if !@user.requested?(course) %>
                <%= render 'request', course: course %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<%= stylesheet_link_tag "show_details.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<%= stylesheet_link_tag "table_design.css" %>
<ul>
     <li class="left"><a class="active">Home</a></li>
     <li class="left"><%= link_to "Transcript", courses_user_path(current_user) %></li>
     <li class="left"><%= link_to "Course Request", request_course_user_path(current_user) %></li>
     <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
     <li class="right"><a><%= current_user.name %></a></li>
</ul>

<p id="notice"><%= notice %></p>

<div class = "show">
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Roll:</strong>
  <%= @user.roll %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>
</div>  

<br>
<hr>

<h2 style="text-align:center; margin-top:10px; color: red">Pre-Registration Dates for 2016-17 2nd Semester</h2>
<h2 style="text-align:center; color: purple">1st November 2016 - 8th November 2016</h2>

<hr>

<h2 style="text-align:center; margin-top:30px">Courses Offered Next Semester</h2>

<table>
  <thead>
    <tr>
      <th>Dept</th>
      <th>Code</th>
      <th>Title</th>
      <th>Instructor</th>
      <th>Email</th>
      <th>Credit</th>
      <th>Timing</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.dept %></td>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= course.instructor %></td>
        <td><%= course.email %></td>
        <td><%= course.credit %></td>
        <td><%= course.timing %></td>
        <td><%= link_to 'Show', course %></td>
      </tr>
    <% end %>
  </tbody>
</table>