config/routes.rb
Rails.application.routes.draw do
  resources :course_stores
  resources :instructors
    resources :requests,    only: [:create, :destroy, :update]
    resources :courses do
        member do
            get :accept_requests
        end
    end
    get 'sessions/new'   
    resources :users do
              member do
            get :request_course
            get :courses
        end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'users#index'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/error', :to => redirect('/404.html')
    get '/error', to:'instructors#show'
end

app/models/course_store.rb
class CourseStore < ApplicationRecord
end

app/controllers/course_stores_controller.rb
class CourseStoresController < ApplicationController
  before_action :set_course_store, only: [:show, :edit, :update, :destroy]

  # GET /course_stores
  # GET /course_stores.json
  def index
    @course_stores = CourseStore.all
  end

  # GET /course_stores/1
  # GET /course_stores/1.json
  def show
  end

  # GET /course_stores/new
  def new
    @course_store = CourseStore.new
  end

  # GET /course_stores/1/edit
  def edit
  end

  # POST /course_stores
  # POST /course_stores.json
  def create
    @course_store = CourseStore.new(course_store_params)

    respond_to do |format|
      if @course_store.save
        format.html { redirect_to @course_store, notice: 'Course store was successfully created.' }
        format.json { render :show, status: :created, location: @course_store }
      else
        format.html { render :new }
        format.json { render json: @course_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_stores/1
  # PATCH/PUT /course_stores/1.json
  def update
    respond_to do |format|
      if @course_store.update(course_store_params)
        format.html { redirect_to @course_store, notice: 'Course store was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_store }
      else
        format.html { render :edit }
        format.json { render json: @course_store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_stores/1
  # DELETE /course_stores/1.json
  def destroy
    @course_store.destroy
    respond_to do |format|
      format.html { redirect_to course_stores_url, notice: 'Course store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_store
      @course_store = CourseStore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_store_params
      params.require(:course_store).permit(:title, :code, :dept, :credit, :grade, :sem, :user_id)
    end
end

app/helpers/course_stores_helper.rb
module CourseStoresHelper
end

app/views/course_stores/_form.html.erb
<%= form_for(course_store) do |f| %>
  <% if course_store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_store.errors.count, "error") %> prohibited this course_store from being saved:</h2>

      <ul>
      <% course_store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :dept %>
    <%= f.text_field :dept %>
  </div>

  <div class="field">
    <%= f.label :credit %>
    <%= f.number_field :credit %>
  </div>

  <div class="field">
    <%= f.label :grade %>
    <%= f.text_field :grade %>
  </div>

  <div class="field">
    <%= f.label :sem %>
    <%= f.text_field :sem %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_stores/edit.html.erb
<h1>Editing Course Store</h1>

<%= render 'form', course_store: @course_store %>

<%= link_to 'Show', @course_store %> |
<%= link_to 'Back', course_stores_path %>

app/views/course_stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Stores</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Dept</th>
      <th>Credit</th>
      <th>Grade</th>
      <th>Sem</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_stores.each do |course_store| %>
      <tr>
        <td><%= course_store.title %></td>
        <td><%= course_store.code %></td>
        <td><%= course_store.dept %></td>
        <td><%= course_store.credit %></td>
        <td><%= course_store.grade %></td>
        <td><%= course_store.sem %></td>
        <td><%= course_store.user_id %></td>
        <td><%= link_to 'Show', course_store %></td>
        <td><%= link_to 'Edit', edit_course_store_path(course_store) %></td>
        <td><%= link_to 'Destroy', course_store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Store', new_course_store_path %>

app/views/course_stores/new.html.erb
<h1>New Course Store</h1>

<%= render 'form', course_store: @course_store %>

<%= link_to 'Back', course_stores_path %>

app/views/course_stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course_store.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= @course_store.code %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @course_store.dept %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @course_store.credit %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @course_store.grade %>
</p>

<p>
  <strong>Sem:</strong>
  <%= @course_store.sem %>
</p>

<p>
  <strong>User:</strong>
  <%= @course_store.user_id %>
</p>

<%= link_to 'Edit', edit_course_store_path(@course_store) %> |
<%= link_to 'Back', course_stores_path %>