config/routes.rb
Rails.application.routes.draw do
  resources :course_stores
  resources :instructors
    resources :requests,    only: [:create, :destroy, :update]
    resources :courses do
        member do
            get :accept_requests
        end
    end
    get 'sessions/new'   
    resources :users do
              member do
            get :request_course
            get :courses
        end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'users#index'
    get '/login', to:'sessions#new'
    post '/login', to:'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/error', :to => redirect('/404.html')
    get '/error', to:'instructors#show'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy] 
  before_action :logged_in_user, only: [:new,:edit,:create,:update,:destroy, :accept_requests] 
  before_action :correct_user_admin, only: [:new,:edit,:create,:update,:destroy]
  before_action :correct_instructor, only: [:accept_requests]
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def accept_requests
    @course = Course.find(params[:id])
    @requested_users = @course.users
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
    def logged_in_user
        unless logged_in?
            store_location
            redirect_to login_url
        end
    end

    def correct_instructor
        @course = Course.find(params[:id]);
        redirect_to(root_url) unless instructor_right?(@course)
    end

    def correct_user_admin
        redirect_to(root_url) unless current_user_admin?
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:dept, :code,:email, :title, :instructor, :credit, :timing)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_accept.html.erb
<%= form_for(Request.find_by(course_id: @course.id, user_id: user.id),
             html: { method: :put }) do |f| %>
  <div><%= hidden_field_tag :status, "Accepted" %></div>
  <%= f.submit "Accept", class: "btn" %>
<% end %>

app/views/courses/_form.html.erb
<%= stylesheet_link_tag "form_design.css" %>
<div class="form_design">
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dept %>
    <%= f.text_field :dept %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :instructor %>
    <%= f.text_field :instructor %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>



  <div class="field">
    <%= f.label :credit %>
    <%= f.number_field :credit %>
  </div>

  <div class="field">
    <%= f.label :timing %>
    <%= f.radio_button :timing, '8:00 AM-9:00 AM MWF' %>8:00 AM - 9:00 AM MWF <br />
    <%= f.radio_button :timing, '9:00 AM -10:00 AM MTTh' %>9:00 AM - 10:00 AM MTTh<br />
    <%= f.radio_button :timing, '10:00 AM - 11:00 AM TWF' %> 10:00 AM - 11:00 AM TWF<br />
    <%= f.radio_button :timing, '12:00 PM - 1:00 PM TWTh' %>12:00 PM - 1:00 PM TWTh<br />
    <%= f.radio_button :timing, '5:00 PM -6:00 PM MTF'%>5:00 PM - 6:00 PM MTF<br />
   </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>  

app/views/courses/_reject.html.erb
<%= form_for(user.course_requests.find_by(course_id: @course.id),
             html: { method: :put }) do |f| %>
  <div><%= hidden_field_tag :status, "Rejected" %></div>
  <%= f.submit "Reject", class: "btn" %>
<% end %>

app/views/courses/accept_requests.html.erb
<%= stylesheet_link_tag "table_design.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<ul>
     <li class="left"><%= link_to 'Home', instructor_path(current_user) %></li>
     <li class="left"><%= link_to 'Edit Personal Details', edit_instructor_path(current_user) %></li>
     <li class="left"><%= link_to 'List of All Instructors', instructors_path(current_user) %></li>
     <li class="left active"><%= link_to "Course Requests", accept_requests_course_path(current_user) %></li>
     <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
     <li class="right"><a><%= current_user.name %></a></li>
</ul>
<p id="notice"><%= notice %></p>

<h1>Pending Requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Roll</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requested_users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.roll %></td>
        <td> <% if !@course.accepted?(user) %>
                <%= render 'accept', user: user %>
            <% end %>
        </td>
        <td>    
            <%= render 'reject', user: user %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<%= stylesheet_link_tag "table_design.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<ul>
    <li class="left"><%= link_to 'Home', login_path(current_user) %></li>
    <li class="left active"><a>Course List</a></li>
    <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
    <li class="right"><a><%= current_user.name %></a></li>
</ul>    
<p id="notice"><%= notice %></p>
<h1>Courses Offered Next Semester</h1>

<table>
  <thead>
    <tr>
      <th>Dept</th>
      <th>Code</th>
      <th>Title</th>
      <th>Instructor</th>
      <th>Email</th>
      <th>Credit</th>
      <th>Timing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.dept %></td>
        <td><%= course.code %></td>
        <td><%= course.title %></td>
        <td><%= course.instructor %></td>
        <td><%= course.email %></td>
        <td><%= course.credit %></td>
        <td><%= course.timing %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<%= stylesheet_link_tag "show_details.css" %>
<%= stylesheet_link_tag "navigation_bar.css" %>
<p id="notice"><%= notice %></p>

<ul>
     <li class="left"><%= link_to 'Home', login_path(current_user) %></li>
     <li class="left"><%= link_to 'Course List', courses_path %></a></li>
     <li class="left"><%= link_to 'Log Out', logout_path, method: "delete" %></li>
     <li class="right"><a><%= current_user.name %></a></li>
</ul>

<div class="show">
<p>
  <strong>Dept:</strong>
  <%= @course.dept %>
</p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @course.instructor %>
</p>

<p>
  <strong>Email:</strong>
  <%= @course.email %>
</p>


<p>
  <strong>Credit:</strong>
  <%= @course.credit %>
</p>

<p>
  <strong>Timing:</strong>
  <%= @course.timing %>
</p>
</div>
<br>
<hr>
<p style="color:red; font-size:15px; text-align: center"><%= link_to 'Edit Course Details', edit_course_path(@course) %><br><br><strong>(Admin Acess Only)</strong></p>